### ISSUE TITLE
something went wrong when I run roslaunch

### ISSUE THREAD

**Issue by Mafumaful** [indra4837/yolov4_trt_ros#21]
nvidia@nvidia-desktop:~$ roslaunch yolov4_trt_ros yolov4_trt.launch 
... logging to /home/nvidia/.ros/log/c52fbab6-92fa-11ec-9d08-48b02d15fa07/roslaunch-nvidia-desktop-14376.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nvidia-desktop:35351/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /yolov4_trt_node/category_number: 3
 * /yolov4_trt_node/confidence_threshold: 0.5
 * /yolov4_trt_node/input_shape: 416
 * /yolov4_trt_node/model: yolov4-tiny
 * /yolov4_trt_node/model_path: /home/nvidia/vola...
 * /yolov4_trt_node/show_image: True
 * /yolov4_trt_node/video_topic: /video_source/raw

NODES
  /
    yolov4_trt_node (yolov4_trt_ros/trt_yolo_v4.py)

ROS_MASTER_URI=http://localhost:11311

process[yolov4_trt_node-1]: started with pid [14393]
Traceback (most recent call last):
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/trt_yolo_v4.py", line 173, in <module>
    main()
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/trt_yolo_v4.py", line 163, in main
    yolo = yolov4()
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/trt_yolo_v4.py", line 33, in __init__
    (self.model_path + self.model), (self.h, self.w), self.category_num)
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/utils/yolo_with_plugins.py", line 220, in __init__
    self.engine, grid_sizes)
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/utils/yolo_with_plugins.py", line 258, in allocate_buffers
    3 * 7 * engine.max_batch_size
AssertionError
Exception ignored in: <bound method TrtYOLO.__del__ of <utils.yolo_with_plugins.TrtYOLO object at 0x7f8cb90f28>>
Traceback (most recent call last):
  File "/home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/utils/yolo_with_plugins.py", line 224, in __del__
    del self.outputs
AttributeError: outputs
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
[yolov4_trt_node-1] process has died [pid 14393, exit code -6, cmd /home/nvidia/volansjiahang/src/mid/image_process/yolov4_trt_ros/trt_yolo_v4.py __name:=yolov4_trt_node __log:=/home/nvidia/.ros/log/c52fbab6-92fa-11ec-9d08-48b02d15fa07/yolov4_trt_node-1.log].
log file: /home/nvidia/.ros/log/c52fbab6-92fa-11ec-9d08-48b02d15fa07/yolov4_trt_node-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Mafumaful** [comment]
hello, when I run this launch file, I met the problem. 
current environment:
+ Jetson Xavier NX
+ ROS Melodic
+ TensorRT 7+

And when I run this code for the first time, I found the .trt file name must be replaced by yolov4Custom-416.

I used yolov4-tinny and I think that this could be the cause.

best wishes :)
